name: ci

on:
    push:
        branches: [main]
    pull_request_target:
        branches: [main]

jobs:
  tests:
    name: Tests with Foundry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Huff Neo Compiler
        uses: cakevm/huff-neo-toolchain@v1

      - name: Run Tests
        run: forge test

  scripts:
    name: Run Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Huff Neo Compiler
        uses: cakevm/huff-neo-toolchain@v1

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run scripts
        run: |
          ls -lsa
          ls script/
          for file in script/*; do
            forge script $file
          done
